# -*- coding: utf-8 -*-
USERNAME_LEN_MIN = 4
USERNAME_LEN_MAX = 32

REALNAME_LEN_MIN = 4
REALNAME_LEN_MAX = 32

PASSWORD_LEN_MIN = 6
PASSWORD_LEN_MAX = 64

AGE_MIN = 1
AGE_MAX = 200

TAG_LENGTH_MAX = 8

USER_AVATAR_DEFAULT = 'user/avatar/default'
USER_TITLE_DEFAULT = u'还没有填写'

TEAM_AVATAR_DEFAULT = 'team/avatar/default/'
TEAM_SLOGAN_DEFAULT = u'还没有填写'

RECOVER_PASSWORD_MAX_AGE = 60 * 60 * 24  # 24 hours
